// Cloning

SELECT * FROM OUR_FIRST_DB.PUBLIC.CUSTOMERS;

CREATE TABLE OUR_FIRST_DB.PUBLIC.CUSTOMERS_CLONE
CLONE OUR_FIRST_DB.PUBLIC.CUSTOMERS;

// Validate the data in cloned table:
SELECT * FROM OUR_FIRST_DB.PUBLIC.CUSTOMERS_CLONE;

//Update Cloned Table:
UPDATE OUR_FIRST_DB.PUBLIC.CUSTOMERS_CLONE
SET LAST_NAME = NULL;

---A zero-copy clone only uses extra storage for changes — not for shared, untouched data.
// Cloning a temporary table is not possible:(check the concept of cross  -cope in CHATGPT)

CREATE OR REPLACE TEMPORARY TABLE OUR_FIRST_DB.PUBLIC.TEMP_TABLE(
  id int);

SELECT * FROM OUR_FIRST_DB.PUBLIC.TEMP_TABLE;

CREATE OR REPLACE TEMPORARY TABLE OUR_FIRST_DB.PUBLIC.TABLE_COPY
CLONE OUR_FIRST_DB.PUBLIC.TEMP_TABLE;

SELECT * FROM OUR_FIRST_DB.PUBLIC.TABLE_COPY;

// Cloning Schema
CREATE OR REPLACE TRANSIENT SCHEMA OUR_FIRST_DB.COPIED_SCHEMA
CLONE OUR_FIRST_DB.PUBLIC;

SELECT * FROM COPIED_SCHEMA.CUSTOMERS;

SHOW TABLES;

SHOW SCHEMAS;

CREATE TRANSIENT SCHEMA OUR_FIRST_DB.EXTERNAL_STAGES_COPIED
CLONE MANAGE_DB.EXTERNAL_STAGES;

// Cloning Database
CREATE TRANSIENT DATABASE OUR_FIRST_DB_COPY
CLONE OUR_FIRST_DB;

DROP DATABASE OUR_FIRST_DB_COPY;
DROP SCHEMA OUR_FIRST_DB.EXTERNAL_STAGES_COPIED;
DROP SCHEMA OUR_FIRST_DB.COPIED_SCHEMA;